"use strict";
/* Sprite bitmaps, drawn for this project.
   '.' transparent   'X' body   'o' shade   'w' highlight

   Dan is 18x32: a uniformed pilot in a peaked cap, rifle held forward, matching the proportions and
   poses of the original's figure: upright stand, a four-phase run with the
   arms counter-swinging, a tucked jump, and a low kneel for firing under fire.
   The Treens are a squatter, heavier silhouette so they read differently at a
   glance even when both are a single colour. */

const SPR = {};
function defineSprite(name, rows) { SPR[name] = { w: rows[0].length, h: rows.length, rows }; }

// ------------------------------------------------------------------ Dan 18x32

defineSprite("dan_stand", [
  ".....XXXXXXXX.....",
  "....XXXXXXXXXX....",
  "....XXXXXXXXXXXXo.",
  ".....XXXXXXXX.....",
  "......XXX.XXX.....",
  "......XXXXXXX.....",
  ".......XXXXX......",
  "........XXX.......",
  ".....XXXXXXXXX....",
  "....XXXXXXXXXXX...",
  "....XXXXXXXXXXX...",
  "....XXX.XXXXXXXX..",
  "....XXX.XXXXXXXXX.",
  "....XXX..XXXooooo.",
  "....XXX..XXXXoooo.",
  "....XXXooXXXXX....",
  "....XXXXXXXXXX....",
  ".....XXXXXXXXX....",
  ".....XXXX.XXXX....",
  ".....XXXX.XXXX....",
  ".....XXXX.XXXX....",
  ".....XXXX.XXXX....",
  ".....XXX...XXX....",
  ".....XXX...XXX....",
  ".....XXX...XXX....",
  ".....XXX...XXX....",
  ".....XXX...XXX....",
  ".....XXX...XXX....",
  "....XXXX...XXXX...",
  "....XXXX...XXXX...",
  "...XXXXX...XXXXX..",
  "...ooooo...ooooo..",
]);

defineSprite("dan_run1", [
  ".....XXXXXXXX.....",
  "....XXXXXXXXXX....",
  "....XXXXXXXXXXXXo.",
  ".....XXXXXXXX.....",
  "......XXX.XXX.....",
  "......XXXXXXX.....",
  ".......XXXXX......",
  "........XXX.......",
  ".....XXXXXXXXX....",
  "....XXXXXXXXXXX...",
  "...XXXXXXXXXXXX...",
  "...XXX..XXXXXXXX..",
  "...XX...XXXXXXXXX.",
  "........XXXXooooo.",
  "........XXXXXoooo.",
  ".......XXXooXXX...",
  ".......XXXXXXX....",
  "......XXXXXXXX....",
  ".....XXXXX.XXXX...",
  "....XXXX....XXXX..",
  "...XXXX......XXXX.",
  "...XXX........XXX.",
  "..XXX..........XXX",
  "..XXX..........XXX",
  ".XXX............XX",
  ".XXX............XX",
  "XXX..............X",
  "XXX...............",
  "XX................",
  "XX................",
  "XX................",
  "oo................",
]);

defineSprite("dan_run2", [
  ".....XXXXXXXX.....",
  "....XXXXXXXXXX....",
  "....XXXXXXXXXXXXo.",
  ".....XXXXXXXX.....",
  "......XXX.XXX.....",
  "......XXXXXXX.....",
  ".......XXXXX......",
  "........XXX.......",
  ".....XXXXXXXXX....",
  "....XXXXXXXXXXX...",
  "....XXXXXXXXXXX...",
  "....XXX.XXXXXXXX..",
  "....XXX.XXXXXXXXX.",
  "....XXX..XXXooooo.",
  "....XXX..XXXXoooo.",
  "....XXXooXXXXX....",
  "....XXXXXXXXXX....",
  ".....XXXXXXXXX....",
  ".....XXXXXXXX.....",
  ".....XXXXXXX......",
  ".....XXXX.XXX.....",
  "....XXXX...XXX....",
  "....XXX....XXXX...",
  "...XXX......XXX...",
  "...XXX.......XXX..",
  "..XXX........XXX..",
  "..XXX.........XX..",
  ".XXX..........XXX.",
  ".XXX...........XX.",
  "XXXX...........XXX",
  "oooo...........ooo",
  "..................",
]);

defineSprite("dan_run3", [
  ".....XXXXXXXX.....",
  "....XXXXXXXXXX....",
  "....XXXXXXXXXXXXo.",
  ".....XXXXXXXX.....",
  "......XXX.XXX.....",
  "......XXXXXXX.....",
  ".......XXXXX......",
  "........XXX.......",
  ".....XXXXXXXXX....",
  "....XXXXXXXXXXX...",
  "...XXXXXXXXXXXX...",
  "...XXX..XXXXXXXX..",
  "...XX...XXXXXXXXX.",
  "........XXXXooooo.",
  "........XXXXXoooo.",
  ".......XXXooXXX...",
  ".......XXXXXXX....",
  "......XXXXXXXX....",
  ".....XXXX.XXXXX...",
  "....XXXX....XXXX..",
  "...XXXX......XXXX.",
  "...XXX........XXX.",
  "..XXX..........XXX",
  "..XXX..........XXX",
  ".XXX............XX",
  ".XXX............XX",
  "XXX..............X",
  "XXX...............",
  "XX................",
  "XX................",
  "XX................",
  "oo................",
]);

defineSprite("dan_run4", [
  ".....XXXXXXXX.....",
  "....XXXXXXXXXX....",
  "....XXXXXXXXXXXXo.",
  ".....XXXXXXXX.....",
  "......XXX.XXX.....",
  "......XXXXXXX.....",
  ".......XXXXX......",
  "........XXX.......",
  ".....XXXXXXXXX....",
  "....XXXXXXXXXXX...",
  "....XXXXXXXXXXX...",
  "....XXX.XXXXXXXX..",
  "....XXX.XXXXXXXXX.",
  "....XXX..XXXooooo.",
  "....XXX..XXXXoooo.",
  "....XXXooXXXXX....",
  "....XXXXXXXXXX....",
  ".....XXXXXXXXX....",
  ".....XXXXXXXX.....",
  ".....XXXXXXX......",
  ".....XXX.XXXX.....",
  "....XXX...XXXX....",
  "...XXXX....XXX....",
  "...XXX......XXX...",
  "..XXX.......XXX...",
  "..XXX........XXX..",
  "..XX.........XXX..",
  ".XXX..........XXX.",
  ".XX...........XXX.",
  "XXX...........XXXX",
  "ooo...........oooo",
  "..................",
]);

defineSprite("dan_jump", [
  ".....XXXXXXXX.....",
  "....XXXXXXXXXX....",
  "....XXXXXXXXXXXXo.",
  ".....XXXXXXXX.....",
  "......XXX.XXX.....",
  "......XXXXXXX.....",
  ".......XXXXX......",
  "........XXX.......",
  ".....XXXXXXXXX....",
  "....XXXXXXXXXXX...",
  "...XXXXXXXXXXXX...",
  "...XXX..XXXXXXXX..",
  "...XX...XXXXXXXXX.",
  "........XXXXooooo.",
  "........XXXXXoooo.",
  ".......XXXooXXX...",
  ".......XXXXXXX....",
  "......XXXXXXXX....",
  ".....XXXXXXXXXX...",
  "....XXXX...XXXXX..",
  "...XXXX.....XXXX..",
  "...XXX.......XXXX.",
  "..XXX.........XXX.",
  "..XX...........XXX",
  "..XX...........XXX",
  ".XXX............XX",
  ".oo.............oo",
  "..................",
  "..................",
  "..................",
  "..................",
  "..................",
]);

defineSprite("dan_kneel", [
  "..................",
  "..................",
  "..................",
  "..................",
  "..................",
  "..................",
  "..................",
  "..................",
  "..................",
  "..................",
  ".....XXXXXXXX.....",
  "....XXXXXXXXXX....",
  "....XXXXXXXXXXXXo.",
  ".....XXXXXXXX.....",
  "......XXX.XXX.....",
  "......XXXXXXX.....",
  ".......XXXXX......",
  "........XXX.......",
  ".....XXXXXXXXX....",
  "....XXXXXXXXXXX...",
  "...XXXXXXXXXXXXX..",
  "...XXX..XXXXXXXXX.",
  "...XX...XXXXooooo.",
  "........XXXXXoooo.",
  ".......XXXooXXX...",
  "......XXXXXXXXX...",
  ".....XXXXXXXXXXX..",
  "....XXXX....XXXXX.",
  "...XXXX......XXXX.",
  "..XXXXX.......XXX.",
  ".XXXXXX........XXX",
  ".oooooo........ooo",
]);

// --------------------------------------------------------------- Treen 20x32

defineSprite("treen_stand", [
  "......XXXXXX........",
  ".....XXXXXXXX.......",
  ".....XXXXXXXX.......",
  ".....XXXXXXXXX......",
  ".....XXoXXXXXX......",
  ".....XXXXXXXXX......",
  "......XXXXXXX.......",
  ".......XXXXX........",
  "........XXX.........",
  "........XXX.........",
  "......XXXXXXX.......",
  ".....XXXXXXXXX......",
  ".....XXX.XXXXXXX....",
  ".....XXX.XXXXXXXXX..",
  ".....XXX..XXXooooooo",
  ".....XXX..XXXXoooo..",
  ".....XXXXXXXXX......",
  "......XXXXXXX.......",
  "......XXXXXXX.......",
  "......XX...XX.......",
  "......XX...XX.......",
  "......XX...XX.......",
  ".....XX.....XX......",
  ".....XX.....XX......",
  ".....XX.....XX......",
  "....XX.......XX.....",
  "....XX.......XX.....",
  "....XX.......XX.....",
  "...XXX.......XXX....",
  "...XXX.......XXX....",
  "..XXXX.......XXXX...",
  "..oooo.......oooo...",
]);

defineSprite("treen_walk", [
  "......XXXXXX........",
  ".....XXXXXXXX.......",
  ".....XXXXXXXX.......",
  ".....XXXXXXXXX......",
  ".....XXoXXXXXX......",
  ".....XXXXXXXXX......",
  "......XXXXXXX.......",
  ".......XXXXX........",
  "........XXX.........",
  "........XXX.........",
  "......XXXXXXX.......",
  ".....XXXXXXXXX......",
  ".....XXX.XXXXXXX....",
  ".....XXX.XXXXXXXXX..",
  ".....XXX..XXXooooooo",
  ".....XXX..XXXXoooo..",
  ".....XXXXXXXXX......",
  "......XXXXXXX.......",
  "......XXXXXXXX......",
  ".....XXX...XXXX.....",
  "....XXX.....XXXX....",
  "...XXX........XXX...",
  "...XX..........XXX..",
  "..XX............XX..",
  "..XX.............XX.",
  ".XX..............XX.",
  ".XX...............XX",
  "XXX...............XX",
  "XX................XX",
  "XX................XX",
  "XX................XX",
  "oo................oo",
]);

// -------------------------------------------------------------------- objects

defineSprite("key", [
  "...XXXX...",
  "..XwwwwX..",
  ".XwXXXXwX.",
  ".XwXooXwX.",
  ".XwXXXXwX.",
  "..XwwwwX..",
  "...XwwX...",
  "...XwwXXX.",
  "...XwwX.X.",
  "...XXXX.X.",
]);

defineSprite("energy", [
  "...XXXX...",
  "..XwwwwX..",
  ".XwoooowX.",
  "XwooXXoowX",
  "XwoXXXXowX",
  "XwooXXoowX",
  ".XwoooowX.",
  "..XwwwwX..",
  "...XXXX...",
  "..........",
]);

/** Draw a sprite a pixel at a time. `flip` mirrors it horizontally. */
function drawSprite(ctx, name, x, y, colours, flip) {
  const s = SPR[name];
  if (!s) return;
  const { rows, w, h } = s;
  for (let j = 0; j < h; j++) {
    const row = rows[j];
    for (let i = 0; i < w; i++) {
      const ch = row[i];
      if (ch === ".") continue;
      const col = ch === "X" ? colours.main : ch === "o" ? colours.shade : colours.light;
      if (!col) continue;
      ctx.fillStyle = col;
      ctx.fillRect(x + (flip ? w - 1 - i : i), y + j, 1, 1);
    }
  }
}

function spriteSize(name) {
  const s = SPR[name];
  return s ? { w: s.w, h: s.h } : { w: 0, h: 0 };
}
